@extends('layouts.auth')
@section('title', __('auth.page_title'))
@section('body-class', 'auth-cinematic')
@section('hide-language-selector', 'true')
@section('content')
    <div class="login-heading"><span class="lock-mark" aria-hidden="true"><svg viewBox="0 0 28 28" fill="none"><rect x="5" y="12" width="18" height="13" rx="3" fill="currentColor"/><path d="M9 12V9a5 5 0 0 1 10 0v3" stroke="currentColor" stroke-width="3" stroke-linecap="round"/><path d="M14 17v4" stroke="white" stroke-width="2" stroke-linecap="round"/></svg></span><h2 id="auth-title">{{ __('auth.title') }}</h2><p>{{ __('auth.subtitle') }}</p></div>
    @if (session('status'))<div class="auth-alert success" role="status">{{ session('status') }}</div>@endif
    <form method="POST" action="{{ route('login.store') }}" class="login-form" data-submit-once novalidate>
        @csrf
        <div class="field-group"><label for="email">{{ __('auth.email') }}</label><div class="input-wrap @error('email') has-error @enderror"><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M4 6.5h16v11H4z" stroke="currentColor" stroke-width="1.8"/><path d="m5 8 7 5 7-5" stroke="currentColor" stroke-width="1.8"/></svg><input id="email" name="email" type="email" value="{{ old('email') }}" autocomplete="email" placeholder="{{ __('auth.email_placeholder') }}" required autofocus @error('email') aria-invalid="true" aria-describedby="email-error" @enderror></div>@error('email')<p class="field-error" id="email-error" role="alert">{{ $message }}</p>@enderror</div>
        <div class="field-group"><label for="password">{{ __('auth.password') }}</label><div class="input-wrap @error('password') has-error @enderror"><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><rect x="5" y="10" width="14" height="11" rx="2" stroke="currentColor" stroke-width="1.8"/><path d="M8 10V7a4 4 0 0 1 8 0v3M12 14v3" stroke="currentColor" stroke-width="1.8"/></svg><input id="password" name="password" type="password" autocomplete="current-password" placeholder="{{ __('auth.password_placeholder') }}" required @error('password') aria-invalid="true" aria-describedby="password-error" @enderror><button class="password-toggle" type="button" data-password-toggle aria-controls="password" aria-label="{{ __('auth.show_password') }}" data-label-show="{{ __('auth.show_password') }}" data-label-hide="{{ __('auth.hide_password') }}"><svg class="eye-open" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z" stroke="currentColor" stroke-width="1.8"/><circle cx="12" cy="12" r="2.5" stroke="currentColor" stroke-width="1.8"/></svg><svg class="eye-closed" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M3 3l18 18M10.6 6.2A10.8 10.8 0 0 1 12 6c6 0 9.5 6 9.5 6a17 17 0 0 1-2.3 3M6.2 6.2C3.8 8 2.5 12 2.5 12s3.5 6 9.5 6a9.8 9.8 0 0 0 3.2-.5M9.8 9.8a3 3 0 0 0 4.4 4.4" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg></button></div>@error('password')<p class="field-error" id="password-error" role="alert">{{ $message }}</p>@enderror</div>
        <div class="form-options"><label class="remember-option"><input type="checkbox" name="remember" value="1" @checked(old('remember'))><span class="custom-checkbox" aria-hidden="true"><svg viewBox="0 0 16 16" fill="none"><path d="m4 8 2.5 2.5L12 5" stroke="currentColor" stroke-width="2"/></svg></span>{{ __('auth.remember') }}</label><a class="forgot-link" href="{{ route('password.request') }}">{{ __('auth.forgot') }}</a></div>
        <button class="login-button" type="submit" data-loading-text="{{ __('auth.submitting') }}"><span data-button-label>{{ __('auth.submit') }}</span><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 12h14m-5-5 5 5-5 5" stroke="currentColor" stroke-width="2"/></svg></button>
    </form>
    <div class="auth-separator" aria-hidden="true"><span>{{ __('auth.professional_access') }}</span></div>
    <div class="info-note access-note"><span class="info-icon" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none"><path d="M16 20v-1.5a4 4 0 0 0-4-4H7a4 4 0 0 0-4 4V20M9.5 11a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Zm7.5-1a3 3 0 0 0 0-5.8M21 20v-1.5a4 4 0 0 0-3-3.9" stroke="currentColor" stroke-width="1.7"/></svg></span><span><strong>{{ __('auth.roles') }}</strong><small>{{ __('auth.platform') }}</small></span></div>
    <div class="info-note security-note"><span class="info-icon" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none"><path d="M12 3 5 6v5c0 4.4 2.7 8.3 7 10 4.3-1.7 7-5.6 7-10V6l-7-3Z" stroke="currentColor" stroke-width="1.8"/><path d="m9 12 2 2 4-4" stroke="currentColor" stroke-width="1.8"/></svg></span><span><strong>{{ __('auth.secure_title') }}</strong><small>{{ __('auth.secure_text') }}</small></span></div>
@endsection
