@extends('layouts.auth')
@section('title', __('auth.reset_form.page_title'))
@section('card-class', 'auth-flow-card')
@section('content')
    <div class="login-heading"><span class="lock-mark" aria-hidden="true"><svg viewBox="0 0 28 28" fill="none"><rect x="5" y="12" width="18" height="13" rx="3" fill="currentColor"/><path d="M9 12V9a5 5 0 0 1 10 0v3" stroke="currentColor" stroke-width="3"/><path d="M14 17v4" stroke="white" stroke-width="2"/></svg></span><h2 id="auth-title">{{ __('auth.reset_form.title') }}</h2><p>{{ __('auth.reset_form.subtitle') }}</p></div>
    <form method="POST" action="{{ route('password.update') }}" class="login-form" data-submit-once novalidate>@csrf<input type="hidden" name="token" value="{{ $token }}"><div class="field-group"><label for="email">{{ __('auth.email') }}</label><div class="input-wrap @error('email') has-error @enderror"><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M4 6.5h16v11H4z" stroke="currentColor" stroke-width="1.8"/><path d="m5 8 7 5 7-5" stroke="currentColor" stroke-width="1.8"/></svg><input id="email" name="email" type="email" value="{{ old('email', $email) }}" autocomplete="email" required readonly @error('email') aria-invalid="true" aria-describedby="reset-email-error" @enderror></div>@error('email')<p class="field-error" id="reset-email-error" role="alert">{{ $message }}</p>@enderror</div>
        @foreach (['password' => __('auth.reset_form.password'), 'password_confirmation' => __('auth.reset_form.confirm')] as $field => $label)<div class="field-group"><label for="{{ $field }}">{{ $label }}</label><div class="input-wrap @error($field) has-error @enderror"><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><rect x="5" y="10" width="14" height="11" rx="2" stroke="currentColor" stroke-width="1.8"/><path d="M8 10V7a4 4 0 0 1 8 0v3" stroke="currentColor" stroke-width="1.8"/></svg><input id="{{ $field }}" name="{{ $field }}" type="password" autocomplete="new-password" required><button class="password-toggle" type="button" data-password-toggle aria-controls="{{ $field }}" aria-label="{{ __('auth.show_password') }}" data-label-show="{{ __('auth.show_password') }}" data-label-hide="{{ __('auth.hide_password') }}"><svg class="eye-open" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z" stroke="currentColor" stroke-width="1.8"/><circle cx="12" cy="12" r="2.5" stroke="currentColor" stroke-width="1.8"/></svg></button></div>@error($field)<p class="field-error" role="alert">{{ $message }}</p>@enderror</div>@endforeach
        <button class="login-button" type="submit" data-loading-text="{{ __('auth.reset_form.submitting') }}"><span data-button-label>{{ __('auth.reset_form.submit') }}</span></button></form>
@endsection
